### ISSUE TITLE
Polarization support 

### ISSUE THREAD

**Issue by telegraphic** [UCBerkeleySETI/blimpy#193] opened 2021-03-22 02:28 UTC
Opening an issue to track progress on polarization support.

Here is a small filterbank file with NIFS=4 generated using `fbgen`:
[test_ifs.fil.zip](https://github.com/UCBerkeleySETI/blimpy/files/6179035/test_ifs.fil.zip)

* [x] Put the test_ifs.fil file in same place as other test data (@mattlebofsky?)
* [x] Update the test data downloader to curl test_ifs.fil.
* [x] Update tests/data.py to define the file for use by test programs.
* [ ] Define an end-state in detail for Filterbank (.fil) and HDF5 (.h5) support.  Under what circumstances should the entire spectra (all polarisations) be read?  Ditto for a specified single polarisation.  Ditto about writing.
* [ ] Does blimpy need a function that produces a single summed spectra utility function?  If so, is that simply a mean  of the respective columns of the polarisation arrays, producing an nifs-to-1 map?

After the meta questions are answered:
* [ ] Fix waterfall.py.
* [ ] Fix all of the io/*.py files that need amendment.
* [ ] add unit test to check polarization basic reading/writing/plotting using the fbgen filterbank file above
* [ ] add command line argument in `watutil` to allow selecting polarization, e.g. `-P` 
* [ ] add command line argument in `dice` to allow selecting polarization, e.g. `-P` 
* [ ] `calcload` : Currently, it calculates the data size requirement based on one polarisation.  Should it use Waterfall.header['nifs'] in its calculation (assuming all polarisations are loaded)?  A boolean parameter could be added to indicate that a calculation if for only one or for all polarisations.
* [ ] add new plots to show polarization -- and make these available in watutil
* [ ] check turboseti works (it should read if=0 by default)
* [ ] better support in turboseti for polarization (will require updates to turboseti codebase)

**Comment by texadactyl** [comment] 2021-03-22 03:26
@mattlebofsky 
Internet URL:  http://blpd0.ssl.berkeley.edu/Voyager_data/
I know its not Voyager data but it is small and that is where blimpy curls down the test files from.
Please place the file there.  Thanks!

**Comment by mattlebofsky** [comment] 2021-03-25 22:30
test_ifs.fil is now that that directory.

**Comment by texadactyl** [comment] 2021-03-28 02:38
Current state of polarisation in blimpy source code:

**Comment by texadactyl** [comment] 2021-07-16 00:45
Because of the scope of changes and the risk of regression, I suggest deferring this issue to hyperseti.

**Comment by texadactyl** [comment] 2021-09-16 16:39
This is like https://github.com/UCBerkeleySETI/turbo_seti/issues/84

I am going to guess that the following is the current polarisation processing strategy:

Front-ends (E.g. rawspec, certain hashpipe apps) produce single polarisation files for turbo_seti & blimpy.
Hyperseti is the go-to multipolarisation search utility of the future.
So, I am closing this issue for turbo_seti & blimpy.

Of course, this is still a potential subject of discussion.

**Closed by texadactyl** 2021-09-16 16:39 UTC
Labels: enhancement
